package com.voc.insight.service.impl;

import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.voc.insight.ai.AiService;
import com.voc.insight.common.BizException;
import com.voc.insight.common.ResultCode;
import com.voc.insight.dto.TopicSaveDTO;
import com.voc.insight.entity.Topic;
import com.voc.insight.mapper.TopicMapper;
import com.voc.insight.service.TopicService;
import com.voc.insight.vo.TopicExpandVO;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

/**
 * 主题词服务实现。
 * 继承 ServiceImpl 即可获得 IService 提供的 CRUD 基础方法。
 */
@Service
@RequiredArgsConstructor
public class TopicServiceImpl extends ServiceImpl<TopicMapper, Topic> implements TopicService {

    private final AiService aiService;

    @Override
    public List<Topic> listAll() {
        return this.list(new LambdaQueryWrapper<Topic>()
                .orderByDesc(Topic::getHitCount)
                .orderByDesc(Topic::getCreatedAt));
    }

    @Override
    public Topic createTopic(TopicSaveDTO dto) {
        long exists = this.count(new LambdaQueryWrapper<Topic>().eq(Topic::getText, dto.getText().trim()));
        if (exists > 0) {
            throw new BizException(ResultCode.TOPIC_EXISTS);
        }
        Topic topic = new Topic();
        topic.setText(dto.getText().trim());
        topic.setCategory(dto.getCategory());
        topic.setIsActive(dto.getIsActive() == null || dto.getIsActive());
        topic.setHitCount(0);
        topic.setAutoGenerated(false);
        topic.setApproved(true);
        this.save(topic);
        return topic;
    }

    @Override
    public Topic updateTopic(String id, TopicSaveDTO dto) {
        Topic topic = requireTopic(id);
        if (dto.getText() != null) {
            topic.setText(dto.getText().trim());
        }
        if (dto.getCategory() != null) {
            topic.setCategory(dto.getCategory());
        }
        if (dto.getIsActive() != null) {
            topic.setIsActive(dto.getIsActive());
        }
        this.updateById(topic);
        return topic;
    }

    @Override
    public Topic toggle(String id) {
        Topic topic = requireTopic(id);
        topic.setIsActive(!topic.getIsActive());
        this.updateById(topic);
        return topic;
    }

    /**
     * AI 扩展主题词为客户口语表达变体。
     * 新生成的变体以 approved=false、isActive=false 落库，
     * 需人工确认后才参与监控，形成「AI 穷举 → 人工把关 → 命中反馈 → 淘汰低效词」闭环。
     */
    @Override
    @Transactional
    public TopicExpandVO expand(String id) {
        Topic topic = requireTopic(id);
        List<String> variants = aiService.expandTopic(topic.getText());

        Set<String> existingTexts = this.list().stream()
                .map(Topic::getText)
                .collect(Collectors.toSet());

        List<Topic> created = new ArrayList<>();
        for (String v : variants) {
            if (v.equals(topic.getText()) || existingTexts.contains(v)) {
                continue;
            }
            Topic newTopic = new Topic();
            newTopic.setText(v);
            newTopic.setCategory(topic.getCategory());
            newTopic.setAutoGenerated(true);
            newTopic.setApproved(false);
            newTopic.setIsActive(false); // 未确认前不参与监控
            newTopic.setHitCount(0);
            try {
                this.save(newTopic);
                created.add(newTopic);
            } catch (Exception e) {
                // 并发或重复，忽略单条失败
            }
        }

        TopicExpandVO vo = new TopicExpandVO();
        vo.setVariants(variants);
        vo.setCreated(created);
        return vo;
    }

    @Override
    public Topic approve(String id, Boolean approved) {
        Topic topic = requireTopic(id);
        boolean ok = approved == null || approved;
        topic.setApproved(ok);
        topic.setIsActive(ok);
        this.updateById(topic);
        return topic;
    }

    private Topic requireTopic(String id) {
        Topic topic = this.getById(id);
        if (topic == null) {
            throw new BizException(ResultCode.TOPIC_NOT_FOUND);
        }
        return topic;
    }
}
