import { Router } from 'express';
import { prisma } from '../db.js';
import { expandTopic } from '../services/ai.js';

const router = Router();

// 获取所有主题词
router.get('/', async (_req, res) => {
  try {
    const topics = await prisma.topic.findMany({
      orderBy: [{ hitCount: 'desc' }, { createdAt: 'desc' }],
      include: {
        _count: { select: { feedbacks: true } }
      }
    });
    res.json(topics);
  } catch (error) {
    console.error('Error fetching topics:', error);
    res.status(500).json({ error: 'Failed to fetch topics' });
  }
});

// 获取单个主题词
router.get('/:id', async (req, res) => {
  try {
    const topic = await prisma.topic.findUnique({
      where: { id: req.params.id },
      include: {
        feedbacks: { orderBy: { createdAt: 'desc' }, take: 20 }
      }
    });

    if (!topic) {
      return res.status(404).json({ error: 'Topic not found' });
    }

    res.json(topic);
  } catch (error) {
    console.error('Error fetching topic:', error);
    res.status(500).json({ error: 'Failed to fetch topic' });
  }
});

// 创建主题词
router.post('/', async (req, res) => {
  try {
    const { text, category } = req.body;

    if (!text || typeof text !== 'string' || text.trim().length === 0) {
      return res.status(400).json({ error: 'Topic text is required' });
    }

    const topic = await prisma.topic.create({
      data: {
        text: text.trim(),
        category: category?.trim() || null,
        autoGenerated: false,
        approved: true
      }
    });

    res.status(201).json(topic);
  } catch (error: any) {
    if (error.code === 'P2002') {
      return res.status(409).json({ error: 'Topic already exists' });
    }
    console.error('Error creating topic:', error);
    res.status(500).json({ error: 'Failed to create topic' });
  }
});

/**
 * AI 扩展主题词：把书面业务术语翻译为客户口语表达。
 * 新生成的变体以 approved=false 落库，需人工确认后才参与监控，
 * 形成「AI 扩展 → 人工确认 → 命中反馈 → 淘汰低效词」的调优闭环。
 */
router.post('/:id/expand', async (req, res) => {
  try {
    const topic = await prisma.topic.findUnique({ where: { id: req.params.id } });
    if (!topic) {
      return res.status(404).json({ error: 'Topic not found' });
    }

    const variants = await expandTopic(topic.text);
    const existing = await prisma.topic.findMany({ select: { text: true } });
    const existingSet = new Set(existing.map(t => t.text));

    const created = [];
    for (const v of variants) {
      if (v === topic.text || existingSet.has(v)) continue;
      try {
        const row = await prisma.topic.create({
          data: {
            text: v,
            category: topic.category,
            autoGenerated: true,
            approved: false,
            isActive: false // 未确认前不参与监控
          }
        });
        created.push(row);
      } catch {
        // 并发或重复，忽略
      }
    }

    res.json({ variants, created });
  } catch (error) {
    console.error('Error expanding topic:', error);
    res.status(500).json({ error: 'Failed to expand topic' });
  }
});

// 人工确认 / 否决 AI 生成的主题词
router.patch('/:id/approve', async (req, res) => {
  try {
    const { approved } = req.body;
    const topic = await prisma.topic.update({
      where: { id: req.params.id },
      data: {
        approved: approved !== false,
        isActive: approved !== false
      }
    });
    res.json(topic);
  } catch (error: any) {
    if (error.code === 'P2025') {
      return res.status(404).json({ error: 'Topic not found' });
    }
    console.error('Error approving topic:', error);
    res.status(500).json({ error: 'Failed to approve topic' });
  }
});

// 更新主题词
router.put('/:id', async (req, res) => {
  try {
    const { text, category, isActive } = req.body;

    const topic = await prisma.topic.update({
      where: { id: req.params.id },
      data: {
        ...(text && { text: text.trim() }),
        ...(category !== undefined && { category: category?.trim() || null }),
        ...(isActive !== undefined && { isActive })
      }
    });

    res.json(topic);
  } catch (error: any) {
    if (error.code === 'P2025') {
      return res.status(404).json({ error: 'Topic not found' });
    }
    console.error('Error updating topic:', error);
    res.status(500).json({ error: 'Failed to update topic' });
  }
});

// 删除主题词
router.delete('/:id', async (req, res) => {
  try {
    await prisma.topic.delete({ where: { id: req.params.id } });
    res.status(204).send();
  } catch (error: any) {
    if (error.code === 'P2025') {
      return res.status(404).json({ error: 'Topic not found' });
    }
    console.error('Error deleting topic:', error);
    res.status(500).json({ error: 'Failed to delete topic' });
  }
});

// 切换启用状态
router.patch('/:id/toggle', async (req, res) => {
  try {
    const topic = await prisma.topic.findUnique({ where: { id: req.params.id } });
    if (!topic) {
      return res.status(404).json({ error: 'Topic not found' });
    }

    const updated = await prisma.topic.update({
      where: { id: req.params.id },
      data: { isActive: !topic.isActive }
    });

    res.json(updated);
  } catch (error) {
    console.error('Error toggling topic:', error);
    res.status(500).json({ error: 'Failed to toggle topic' });
  }
});

export default router;
