package com.voc.insight.entity;

import com.baomidou.mybatisplus.annotation.FieldFill;
import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;

import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * 监控主题词。
 * 业务人员关注的问题主题，支持人工维护与 AI 自动扩展。
 */
@Data
@TableName("topic")
public class Topic implements Serializable {

    /** 主键，UUID */
    @TableId(type = IdType.ASSIGN_UUID)
    private String id;

    /** 主题词 */
    private String text;

    /** 归属类别 */
    private String category;

    /** 是否启用 */
    private Boolean isActive;

    /** 命中次数，驱动关键词调优闭环 */
    private Integer hitCount;

    /** 是否由 AI 扩展生成 */
    private Boolean autoGenerated;

    /** 人工确认状态 */
    private Boolean approved;

    /** 创建时间，插入时自动填充 */
    @TableField(fill = FieldFill.INSERT)
    private LocalDateTime createdAt;

    /** 更新时间，插入与更新时自动填充 */
    @TableField(fill = FieldFill.INSERT_UPDATE)
    private LocalDateTime updatedAt;
}
