const API_BASE = "/api";

import { getToken, clearAuth } from "./auth";

export interface Topic {
  id: string;
  text: string;
  category: string | null;
  isActive: boolean;
  hitCount: number;
  autoGenerated: boolean;
  approved: boolean;
  createdAt: string;
  updatedAt: string;
  _count?: { feedbacks: number };
}

export interface Feedback {
  id: string;
  title: string | null;
  content: string;
  source: string;
  sourceId: string | null;
  url: string | null;
  rating: number | null;
  productLine: string | null;
  language: string | null;
  authorName: string | null;
  publishedAt: string | null;
  createdAt: string;
  sentiment: string;
  topics: string | null;
  urgency: string;
  urgencyReason: string | null;
  aiSummary: string | null;
  confidence: number | null;
  humanLabel: string | null;
  isReviewed: boolean;
  topicId: string | null;
  topic: { id: string; text: string; category: string | null } | null;
}

export interface Alert {
  id: string;
  type: string;
  title: string;
  content: string;
  urgency: string;
  isRead: boolean;
  handled: boolean;
  feedbackId: string | null;
  createdAt: string;
}

export interface Stats {
  total: number;
  today: number;
  negative: number;
  negativeRatio: number;
  pendingAlert: number;
  pendingReview: number;
  avgRating: number | null;
  bySentiment: Record<string, number>;
  bySource: Record<string, number>;
  byProduct: Record<string, number>;
}

export interface InsightReport {
  productLine: string;
  totalFeedback: number;
  avgRating: number | null;
  negativeRatio: number;
  topTopics: { topic: string; count: number; negativeCount: number }[];
  summary: string;
  suggestions: string[];
}

export interface AnalysisResult {
  sentiment: string;
  topics: string[];
  urgency: string;
  urgencyReason: string;
  aiSummary: string;
  confidence: number;
}

/** Java 端统一响应封装 Result{code, message, data, timestamp} */
interface ResultWrapper {
  code: number;
  message: string;
  data: unknown;
}

function isResultWrapper(body: unknown): body is ResultWrapper {
  return (
    typeof body === "object" &&
    body !== null &&
    typeof (body as ResultWrapper).code === "number" &&
    "data" in body
  );
}

/** Java 端分页结构 PageResult{records, current, size, total, pages} */
interface JavaPage<T> {
  records: T[];
  current: number;
  size: number;
  total: number;
  pages: number;
}

function isJavaPage(body: unknown): body is JavaPage<unknown> {
  return (
    typeof body === "object" &&
    body !== null &&
    Array.isArray((body as JavaPage<unknown>).records)
  );
}

interface Pagination {
  page: number;
  limit: number;
  total: number;
  totalPages: number;
}

function toPagination<T>(p: JavaPage<T>): Pagination {
  return {
    page: p.current,
    limit: p.size,
    total: p.total,
    totalPages: p.pages,
  };
}

async function request<T>(
  endpoint: string,
  options: RequestInit = {},
): Promise<T> {
  // 注入 JWT（登录接口本身不需要）
  const token = getToken();
  const authHeaders: Record<string, string> =
    token && endpoint !== "/auth/login"
      ? { Authorization: `Bearer ${token}` }
      : {};

  const response = await fetch(`${API_BASE}${endpoint}`, {
    headers: {
      "Content-Type": "application/json",
      ...authHeaders,
      ...options.headers,
    },
    ...options,
  });

  // 未认证 / token 过期：清除登录态并通知页面跳转登录
  if (response.status === 401 && endpoint !== "/auth/login") {
    clearAuth();
    window.dispatchEvent(new Event("auth:logout"));
    throw new Error("登录已过期，请重新登录");
  }

  if (response.status === 204) {
    return undefined as T;
  }

  const body = await response.json().catch(() => null);

  if (!response.ok) {
    throw new Error(body?.message || body?.error || "Request failed");
  }

  // Java 端返回统一 Result 封装（HTTP 状态恒 200，错误也在 code 里），这里解包；
  // Node 端直返业务数据，原样返回，两端兼容
  if (isResultWrapper(body)) {
    if (body.code !== 0) {
      throw new Error(body.message || "Request failed");
    }
    return body.data as T;
  }
  return body as T;
}

// ============ 主题词 ============
export const topicsApi = {
  getAll: () => request<Topic[]>("/topics"),

  create: (data: { text: string; category?: string }) =>
    request<Topic>("/topics", {
      method: "POST",
      body: JSON.stringify(data),
    }),

  update: (id: string, data: Partial<Topic>) =>
    request<Topic>(`/topics/${id}`, {
      method: "PUT",
      body: JSON.stringify(data),
    }),

  delete: (id: string) => request<void>(`/topics/${id}`, { method: "DELETE" }),

  toggle: (id: string) =>
    request<Topic>(`/topics/${id}/toggle`, { method: "PATCH" }),

  /** AI 扩展主题词为客户口语表达变体 */
  expand: (id: string) =>
    request<{ variants: string[]; created: Topic[] }>(`/topics/${id}/expand`, {
      method: "POST",
    }),

  /** 人工确认 / 否决 AI 生成的变体 */
  approve: (id: string, approved: boolean) =>
    request<Topic>(`/topics/${id}/approve`, {
      method: "PATCH",
      body: JSON.stringify({ approved }),
    }),
};

// ============ 客户反馈 ============
export interface FeedbackQuery {
  page?: number;
  limit?: number;
  source?: string;
  sentiment?: string;
  urgency?: string;
  productLine?: string;
  topicId?: string;
  keyword?: string;
  pendingReview?: string;
  timeRange?: string;
  sortBy?: string;
  sortOrder?: string;
}

export const feedbacksApi = {
  getAll: async (params?: FeedbackQuery) => {
    const searchParams = new URLSearchParams();
    if (params) {
      Object.entries(params).forEach(([key, value]) => {
        if (value !== undefined && value !== "")
          searchParams.append(key, String(value));
      });
    }
    const res = await request<
      { data: Feedback[]; pagination: Pagination } | JavaPage<Feedback>
    >(`/feedbacks?${searchParams}`);
    // Java 端直返 PageResult，映射为前端期望的 { data, pagination } 结构
    if (isJavaPage(res)) {
      return { data: res.records as Feedback[], pagination: toPagination(res) };
    }
    return res;
  },

  getStats: () => request<Stats>("/feedbacks/stats"),

  getById: (id: string) => request<Feedback>(`/feedbacks/${id}`),

  /** 单条文本即时分析，不落库 */
  analyze: (data: {
    content: string;
    productLine?: string;
    rating?: number;
    language?: string;
  }) =>
    request<AnalysisResult>("/feedbacks/analyze", {
      method: "POST",
      body: JSON.stringify(data),
    }),

  /** 导入外部反馈数据（Java 端仅返回 created） */
  import: (content: string, format: "json" | "csv") =>
    request<{ total?: number; created: number }>("/feedbacks/import", {
      method: "POST",
      body: JSON.stringify({ content, format }),
    }),

  /** 生成演示数据 */
  generateDemo: (count: number) =>
    request<{ created: number }>("/feedbacks/generate-demo", {
      method: "POST",
      body: JSON.stringify({ count }),
    }),

  /** 人工复核 */
  review: (
    id: string,
    data: { sentiment?: string; topics?: string[]; urgency?: string },
  ) =>
    request<Feedback>(`/feedbacks/${id}/review`, {
      method: "PATCH",
      body: JSON.stringify(data),
    }),

  /** 评分归因报告 */
  getInsight: (productLine?: string) =>
    request<InsightReport>(
      `/feedbacks/insight${productLine ? `?productLine=${productLine}` : ""}`,
    ),

  delete: (id: string) =>
    request<void>(`/feedbacks/${id}`, { method: "DELETE" }),
};

// ============ 预警 ============
export const alertsApi = {
  getAll: async (params?: {
    page?: number;
    limit?: number;
    unreadOnly?: boolean;
    unhandledOnly?: boolean;
  }) => {
    const searchParams = new URLSearchParams();
    if (params) {
      Object.entries(params).forEach(([key, value]) => {
        if (value !== undefined) searchParams.append(key, String(value));
      });
    }
    const res = await request<{
      data: Alert[];
      unreadCount: number;
      unhandledCount: number;
      pagination: Pagination | JavaPage<Alert>;
    }>(`/alerts?${searchParams}`);
    // Java 端 pagination 为 PageResult 结构，字段名映射
    if (isJavaPage(res.pagination)) {
      return { ...res, pagination: toPagination(res.pagination) };
    }
    return res as {
      data: Alert[];
      unreadCount: number;
      unhandledCount: number;
      pagination: Pagination;
    };
  },

  markAsRead: (id: string) =>
    request<Alert>(`/alerts/${id}/read`, { method: "PATCH" }),

  markAllAsRead: () => request<void>("/alerts/read-all", { method: "PATCH" }),

  handle: (id: string) =>
    request<Alert>(`/alerts/${id}/handle`, { method: "PATCH" }),

  delete: (id: string) => request<void>(`/alerts/${id}`, { method: "DELETE" }),
};

// ============ 设置 ============
export const settingsApi = {
  getAll: () => request<Record<string, string>>("/settings"),

  update: (settings: Record<string, string>) =>
    request<void>("/settings", {
      method: "PUT",
      body: JSON.stringify(settings),
    }),
};

// 手动触发一轮分析（异步：投递到 MQ，消费者并发执行，结果经实时推送到达）
export const triggerInsightCheck = () =>
  request<{ message: string; queued?: number }>("/check-feedbacks", {
    method: "POST",
  });

// ============ 认证 ============
export interface LoginResult {
  token: string;
  username: string;
  role: string;
}

export const authApi = {
  /** 登录，返回 JWT 与角色 */
  login: (username: string, password: string) =>
    request<LoginResult>("/auth/login", {
      method: "POST",
      body: JSON.stringify({ username, password }),
    }),

  /** 当前用户信息 */
  me: () => request<{ username: string; role: string }>("/auth/me"),
};
