const API_BASE = '/api';

export interface Topic {
  id: string;
  text: string;
  category: string | null;
  isActive: boolean;
  hitCount: number;
  autoGenerated: boolean;
  approved: boolean;
  createdAt: string;
  updatedAt: string;
  _count?: { feedbacks: number };
}

export interface Feedback {
  id: string;
  title: string | null;
  content: string;
  source: string;
  sourceId: string | null;
  url: string | null;
  rating: number | null;
  productLine: string | null;
  language: string | null;
  authorName: string | null;
  publishedAt: string | null;
  createdAt: string;
  sentiment: string;
  topics: string | null;
  urgency: string;
  urgencyReason: string | null;
  aiSummary: string | null;
  confidence: number | null;
  humanLabel: string | null;
  isReviewed: boolean;
  topicId: string | null;
  topic: { id: string; text: string; category: string | null } | null;
}

export interface Alert {
  id: string;
  type: string;
  title: string;
  content: string;
  urgency: string;
  isRead: boolean;
  handled: boolean;
  feedbackId: string | null;
  createdAt: string;
}

export interface Stats {
  total: number;
  today: number;
  negative: number;
  negativeRatio: number;
  pendingAlert: number;
  pendingReview: number;
  avgRating: number | null;
  bySentiment: Record<string, number>;
  bySource: Record<string, number>;
  byProduct: Record<string, number>;
}

export interface InsightReport {
  productLine: string;
  totalFeedback: number;
  avgRating: number | null;
  negativeRatio: number;
  topTopics: { topic: string; count: number; negativeCount: number }[];
  summary: string;
  suggestions: string[];
}

export interface AnalysisResult {
  sentiment: string;
  topics: string[];
  urgency: string;
  urgencyReason: string;
  aiSummary: string;
  confidence: number;
}

async function request<T>(endpoint: string, options: RequestInit = {}): Promise<T> {
  const response = await fetch(`${API_BASE}${endpoint}`, {
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    },
    ...options
  });

  if (!response.ok) {
    const error = await response.json().catch(() => ({ error: 'Request failed' }));
    throw new Error(error.error || 'Request failed');
  }

  if (response.status === 204) {
    return undefined as T;
  }

  return response.json();
}

// ============ 主题词 ============
export const topicsApi = {
  getAll: () => request<Topic[]>('/topics'),

  create: (data: { text: string; category?: string }) =>
    request<Topic>('/topics', {
      method: 'POST',
      body: JSON.stringify(data)
    }),

  update: (id: string, data: Partial<Topic>) =>
    request<Topic>(`/topics/${id}`, {
      method: 'PUT',
      body: JSON.stringify(data)
    }),

  delete: (id: string) => request<void>(`/topics/${id}`, { method: 'DELETE' }),

  toggle: (id: string) => request<Topic>(`/topics/${id}/toggle`, { method: 'PATCH' }),

  /** AI 扩展主题词为客户口语表达变体 */
  expand: (id: string) =>
    request<{ variants: string[]; created: Topic[] }>(`/topics/${id}/expand`, { method: 'POST' }),

  /** 人工确认 / 否决 AI 生成的变体 */
  approve: (id: string, approved: boolean) =>
    request<Topic>(`/topics/${id}/approve`, {
      method: 'PATCH',
      body: JSON.stringify({ approved })
    })
};

// ============ 客户反馈 ============
export interface FeedbackQuery {
  page?: number;
  limit?: number;
  source?: string;
  sentiment?: string;
  urgency?: string;
  productLine?: string;
  topicId?: string;
  keyword?: string;
  pendingReview?: string;
  timeRange?: string;
  sortBy?: string;
  sortOrder?: string;
}

export const feedbacksApi = {
  getAll: (params?: FeedbackQuery) => {
    const searchParams = new URLSearchParams();
    if (params) {
      Object.entries(params).forEach(([key, value]) => {
        if (value !== undefined && value !== '') searchParams.append(key, String(value));
      });
    }
    return request<{ data: Feedback[]; pagination: { page: number; limit: number; total: number; totalPages: number } }>(
      `/feedbacks?${searchParams}`
    );
  },

  getStats: () => request<Stats>('/feedbacks/stats'),

  getById: (id: string) => request<Feedback>(`/feedbacks/${id}`),

  /** 单条文本即时分析，不落库 */
  analyze: (data: { content: string; productLine?: string; rating?: number; language?: string }) =>
    request<AnalysisResult>('/feedbacks/analyze', {
      method: 'POST',
      body: JSON.stringify(data)
    }),

  /** 导入外部反馈数据 */
  import: (content: string, format: 'json' | 'csv') =>
    request<{ total: number; created: number }>('/feedbacks/import', {
      method: 'POST',
      body: JSON.stringify({ content, format })
    }),

  /** 生成演示数据 */
  generateDemo: (count: number) =>
    request<{ created: number }>('/feedbacks/generate-demo', {
      method: 'POST',
      body: JSON.stringify({ count })
    }),

  /** 人工复核 */
  review: (id: string, data: { sentiment?: string; topics?: string[]; urgency?: string }) =>
    request<Feedback>(`/feedbacks/${id}/review`, {
      method: 'PATCH',
      body: JSON.stringify(data)
    }),

  /** 评分归因报告 */
  getInsight: (productLine?: string) =>
    request<InsightReport>(`/feedbacks/insight${productLine ? `?productLine=${productLine}` : ''}`),

  delete: (id: string) => request<void>(`/feedbacks/${id}`, { method: 'DELETE' })
};

// ============ 预警 ============
export const alertsApi = {
  getAll: (params?: { page?: number; limit?: number; unreadOnly?: boolean; unhandledOnly?: boolean }) => {
    const searchParams = new URLSearchParams();
    if (params) {
      Object.entries(params).forEach(([key, value]) => {
        if (value !== undefined) searchParams.append(key, String(value));
      });
    }
    return request<{
      data: Alert[];
      unreadCount: number;
      unhandledCount: number;
      pagination: { page: number; limit: number; total: number; totalPages: number };
    }>(`/alerts?${searchParams}`);
  },

  markAsRead: (id: string) => request<Alert>(`/alerts/${id}/read`, { method: 'PATCH' }),

  markAllAsRead: () => request<void>('/alerts/read-all', { method: 'PATCH' }),

  handle: (id: string) => request<Alert>(`/alerts/${id}/handle`, { method: 'PATCH' }),

  delete: (id: string) => request<void>(`/alerts/${id}`, { method: 'DELETE' })
};

// ============ 设置 ============
export const settingsApi = {
  getAll: () => request<Record<string, string>>('/settings'),

  update: (settings: Record<string, string>) =>
    request<void>('/settings', {
      method: 'PUT',
      body: JSON.stringify(settings)
    })
};

// 手动触发一轮分析
export const triggerInsightCheck = () =>
  request<{ message: string }>('/check-feedbacks', { method: 'POST' });
